---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '3.3-jdk-8'

inputs:
- name: roster
- name: version

outputs:
- name: build

run:
  path: roster/ci/tasks/build.sh
