---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: engineerbetter/cf-cli
    tag: 'latest'

inputs:
- name: minio-development
- name: version

outputs:
- name: build

run:
  path: roster/ci/tasks/test.sh

params:
  CF_API_URL:
  CF_USER_NAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SPACE:
  MYSQL_SERVICE_NAME:
  MYSQL_PLAN_NAME:
