---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '3.3-jdk-8'

inputs:
- name: rest-data-service

outputs:
- name: updated-repo

run:
  path: bash
  args:
  - -exc
  - |
    git clone rest-data-service updated-repo
    pushd updated-repo/apps/rest-data-service
      mvn clean package
    popd
